#!/bin/bash

#
# cabeçalho-gui.sh (Shell Script)
#
# Cabeçalho com interface Gráfica
#
# Site https://dirack.github.io
#
# Versão 1.0
#
# Programador: Rodolfo A C Neves (Dirack) 11/02/2025
#
# Email: rodolfo_profissional@hotmail.com
#
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt

NOMEDOPROGRAMA=$(dialog --stdout \
			--inputbox "Digite o nome do programa" \
			0 0)


OBJETIVO=$(dialog --stdout \
			--inputbox "Digite o objetivo do  programa" \
			0 0)
#echo -e "\033[01;32m 1⁰ PASS\033[m"

OP=$(dialog --stdout \
	--radiolist "Opções de Cabeçalho" 0 0 3 \
	"sh" "Shell Script" on "py" "Python" off)
./cabeçalho_linha_comando.sh "-$OP" "$NOMEDOPROGRAMA" -m "$OBJETIVO"

clear
[ -n "$NOMEDOPROGRAMA" ] && echo "$NOMEDOPROGRAMA - Cabeçalho Adicionado !"


